In [1]:
import pandas as pd
import numpy as np

In [2]:
# read dataset into dataframe
dataframe = pd.read_csv("data/METABRIC_RNA_Mutation.csv", sep=",")

/opt/conda/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3169: DtypeWarning: Columns (677,687,689,691) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
# Drop all rows which contain empty cells
dataframe_row_clean = dataframe.dropna(axis=0)

# Drop columns which contain empty cells
dataframe_clean = dataframe_row_clean.dropna(axis=1)

In [4]:
# change column category to categorical
for col in dataframe_clean.columns.tolist():
    dtype = dataframe_clean[col].dtype
    if dtype == "object":
        dataframe_clean[col] = dataframe_clean[col].astype('category')

In [5]:
# encode categoricals to integers
cat_columns = dataframe_clean.select_dtypes(['category']).columns
dataframe_clean[cat_columns] = dataframe_clean[cat_columns].apply(lambda x: x.cat.codes)

In [6]:
dataframe_clean.to_csv("data/METABRIC_RNA_Mutation_clean.csv", index=False)

In [7]:
dataframe_features = pd.read_csv("data/METABRIC_RNA_Mutation_clean.csv", sep=",")

In [8]:
dataframe_features

,age_at_diagnosis,type_of_breast_surgery,cancer_type,cancer_type_detailed,cellularity,chemotherapy,pam50_+_claudin-low_subtype,cohort,er_status_measured_by_ihc,er_status,...,mtap_mut,ppp2cb_mut,smarcd1_mut,nras_mut,ndfip1_mut,hras_mut,prps2_mut,smarcb1_mut,stmn2_mut,siah1_mut
0,43.19,0,0,1,0,0,2,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,76.97,1,0,4,0,1,3,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,78.77,1,0,1,2,0,3,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,86.41,0,0,1,2,0,3,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,84.22,1,0,2,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,71.22,1,0,4,0,0,2,5,1,1,...,0,0,0,0,0,1,0,1,0,1
1088,70.65,0,0,4,0,0,3,5,1,1,...,0,0,0,0,0,1,0,1,0,1
1089,75.62,1,0,1,0,0,0,5,0,0,...,0,0,0,0,0,1,0,1,0,1
1090,52.84,0,0,4,0,1,5,5,1,1,...,0,0,0,0,0,1,0,1,0,1
1091,63.20,0,0,3,0,0,3,5,1,1,...,0,0,0,0,0,1,0,1,0,1